name: Production Build & Deploy
on: 
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/**
      - '**.md'
      - .vscode/**
      - .gitignore
  
  workflow_dispatch:

jobs:
  use-deploy-template:
    name: Build & Deploy
    uses: ./.github/workflows/deploy-template.yml
    with:
      enivronment: production
      deploy_repo: portfolio
      cname: cyril.is-a.dev
    secrets: inherit
    permissions:
      contents: write
