name: Build & Deploy Template
run-name: "Deploy to ${{ inputs.enivronment }}: v${{ inputs.version_number }}"

on:
  workflow_call:
    inputs:
      enivronment:
        required: true
        type: string
        description: The environment to deploy to.
      deploy_repo:
        required: true
        type: string
        description: The name of the repository associated with the environment to deploy to.
      version_number:
        required: false
        type: string
        description: The version number of the deployment.
        default: ${{github.run_id}}.${{ github.run_number }}.${{ github.run_attempt }}
      url:
        required: false
        type: string
        description: The environment's URL.
        default: ${{ github.repository_owner }}.github.io/${{ inputs.deploy_repo }}
      cname:
        required: false
        type: string
        description: The Cannonical Name (CNAME) of the environment.
        default: ${{ inputs.url }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.enivronment }}
      url: https://${{ inputs.url }}
    permissions:
      contents: write
    steps:
      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Checkout Working Repo (${{ github.repository }})
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Checkout Deployment Repo (${{ inputs.deploy_repo }})
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ inputs.deploy_repo }}
          token: ${{ secrets.REPO_PUSH_TOKEN }}
          path: deploy

      - name: Copy Files
        run: cp -r dist/* deploy

      - name: Disable Jekyll
        run: touch deploy/.nojekyll

      - name: Configure CNAME
        run: echo ${{ inputs.cname }} > deploy/CNAME

      - name: Write Version Number
        run: echo ${{ inputs.version_number }} > deploy/.version
      
      - name: Commit & Push
        run: |
          git add .
          git commit -m $GITHUB_SHA
          git push
        working-directory: deploy
