name: Development Build & Deploy
on: 
  push:
    branches:
      - dev
    paths-ignore:
      - .github/workflows/**
      - '**.md'
      - .vscode/**
      - .gitignore

  workflow_dispatch:

jobs:
  use-deploy-template:
    name: Build & Deploy
    uses: ./.github/workflows/deploy-template.yml
    with:
      enivronment: development
      deploy_repo: portfolio-dev
    secrets: inherit
    permissions:
      contents: write
